[versions]
nexusPublish = "2.0.0"

annotations = "26.0.1"
lombok = "1.18.34"

#networking
netty5 = "5.0.0.Alpha5"

# logging
log4j2 = "2.24.1"

[libraries]
lombok = { group = "org.projectlombok", name="lombok", version.ref = "lombok" }
annotations = { group = "org.jetbrains", name="annotations", version.ref = "annotations" }

#networking
netty5 = { group = "io.netty", name = "netty5-all", version.ref = "netty5" }

# logging
log4j2 = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j2" }
log4j2-simple = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j2" }

[plugins]
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublish" }